### ISSUE TITLE
Index out of bounds panic in line index

### ISSUE THREAD

**Issue by tvallotton** [rust-lang/rust-analyzer#10138]
Rust analyzer panicked while commenting some code. I haven't been able to reproduce the issue, but I decided to give you the output just in case. I was commenting either the `ast::Statement` enum or its Display implementation. If it helps the code I had can be found at https://github.com/tvallotton/sqlparser-rs/tree/rust-analyzer-panic.

```
Panic context:
> 
version: d15f646ff 2021-08-30 stable
request: codeLens/resolve CodeLens {
    range: Range {
        start: Position {
            line: 1351,
            character: 11,
        },
        end: Position {
            line: 1351,
            character: 19,
        },
    },
    command: None,
    data: Some(
        Object({
            "impls": Object({
                "textDocument": Object({
                    "uri": String(
                        "file:///Users/tomas/Documents/sqlparser-rs/src/ast/mod.rs",
                    ),
                }),
                "position": Object({
                    "line": Number(
                        1351,
                    ),
                    "character": Number(
                        11,
                    ),
                }),
            }),
        }),
    ),
}

thread '<unnamed>' panicked at 'index out of bounds: the len is 1153 but the index is 1351', crates/ide_db/src/line_index.rs:106:9
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic_bounds_check
   3: rust_analyzer::from_proto::text_range
   4: rust_analyzer::handlers::handle_code_lens_resolve
   5: rust_analyzer::dispatch::RequestDispatcher::on::{{closure}}::{{closure}}
   6: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[Error - 11:44:57 AM] Request codeLens/resolve failed.
  Message: server panicked: index out of bounds: the len is 1153 but the index is 1351
  Code: -32603 
Panic context:
> 
version: d15f646ff 2021-08-30 stable
request: codeLens/resolve CodeLens {
    range: Range {
        start: Position {
            line: 1334,
            character: 9,
        },
        end: Position {
            line: 1334,
            character: 20,
        },
    },
    command: None,
    data: Some(
        Object({
            "impls": Object({
                "textDocument": Object({
                    "uri": String(
                        "file:///Users/tomas/Documents/sqlparser-rs/src/ast/mod.rs",
                    ),
                }),
                "position": Object({
                    "line": Number(
                        1334,
                    ),
                    "character": Number(
                        9,
                    ),
                }),
            }),
        }),
    ),
}

thread '<unnamed>' panicked at 'index out of bounds: the len is 1153 but the index is 1334', crates/ide_db/src/line_index.rs:106:9
Panic context:
> 
version: d15f646ff 2021-08-30 stable
request: codeLens/resolve CodeLens {
    range: Range {
        start: Position {
            line: 1321,
            character: 11,
        },
        end: Position {
            line: 1321,
            character: 21,
        },
    },
    command: None,
    data: Some(
        Object({
            "impls": Object({
                "textDocument": Object({
                    "uri": String(
                        "file:///Users/tomas/Documents/sqlparser-rs/src/ast/mod.rs",
                    ),
                }),
                "position": Object({
                    "line": Number(
                        1321,
                    ),
                    "character": Number(
                        11,
                    ),
                }),
            }),
        }),
    ),
}

thread '<unnamed>' panicked at 'index out of bounds: the len is 1153 but the index is 1321', crates/ide_db/src/line_index.rs:106:9
stack backtrace:
Panic context:
> 
version: d15f646ff 2021-08-30 stable
request: codeLens/resolve CodeLens {
    range: Range {
        start: Position {
            line: 1351,
            character: 11,
        },
        end: Position {
            line: 1351,
            character: 19,
        },
    },
    command: None,
    data: Some(
        Object({
            "impls": Object({
                "textDocument": Object({
                    "uri": String(
                        "file:///Users/tomas/Documents/sqlparser-rs/src/ast/mod.rs",
                    ),
                }),
                "position": Object({
                    "line": Number(
                        1351,
                    ),
                    "character": Number(
                        11,
                    ),
                }),
            }),
        }),
    ),
}

thread '<unnamed>' panicked at 'index out of bounds: the len is 1153 but the index is 1351', crates/ide_db/src/line_index.rs:   0: _rust_begin_unwind106
 :  91: 
core::panicking::panic_fmt
   2: core::panicking::panic_bounds_check
   3: rust_analyzer::from_proto::text_range
   4: rust_analyzer::handlers::handle_code_lens_resolve
   5: rust_analyzer::dispatch::RequestDispatcher::on::{{closure}}::{{closure}}
   6: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic_bounds_check
   3: rust_analyzer::from_proto::text_range
   4: rust_analyzer::handlers::handle_code_lens_resolve
   5: rust_analyzer::dispatch::RequestDispatcher::on::{{closure}}::{{closure}}
   6: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic_bounds_check
   3: rust_analyzer::from_proto::text_range
   4: rust_analyzer::handlers::handle_code_lens_resolve
   5: rust_analyzer::dispatch::RequestDispatcher::on::{{closure}[Error - 11:45:12 AM] Request codeLens/resolve failed.
  Message: server panicked: index out of bounds: the len is 1153 but the index is 1334
  Code: -32603 
}::{{closure}}
   6: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[Error - 11:45:12 AM] Request codeLens/resolve failed.
  Message: server panicked: index out of bounds: the len is 1153 but the index is 1321
  Code: -32603 
[Error - 11:45:12 AM] Request codeLens/resolve failed.
  Message: server panicked: index out of bounds: the len is 1153 but the index is 1351
  Code: -32603 

```

**Comment by tvallotton** [comment]
I think I was able to reproduce it. I wasn't commenting the code, I was deleting it. If you try deleting lines 547-1317 of `src/ast/mod.rs` the panic should occur.

**Comment by lnicola** [comment]
Ugh, this looks bad. And it's not that easy to reproduce, I can't trigger it.

**Comment by lnicola** [comment]
Are you using VS Code?

**Comment by tvallotton** [comment]
I'm using VS Code

**Comment by tvallotton** [comment]
It does not always work, but generally if a save the file recently with `cmd-s` and delete the code it works. I'm trying to see if I can get a simpler example.

**Comment by lnicola** [comment]
Maybe you could try to get a complete LSP trace by setting `RA_LOG=lsp_server=debug,error` and `RA_LOG_FILE` to some path. You can set them in Code, in `rust-analyzer.server.extraEnv`.

If this still works, you should get a trace of every LSP message between Code and the server. We don't have a replay tool yet, but in principle you should be able to reproduce the issue by replaying that log.

**Comment by tvallotton** [comment]
is `rust-analyzer.server.extraEnv` just a file containing this?
```
RA_LOG=lsp_server=debug,error
RA_LOG_FILE
```
At `Rust Analyzer language Server` I get: 
```Panic context:
> 
version: d15f646ff 2021-08-30 stable
request: codeLens/resolve CodeLens {
    range: Range {
        start: Position {
            line: 1321,
            character: 11,
        },
        end: Position {
            line: 1321,
            character: 21,
        },
    },
    command: None,
    data: Some(
        Object({
            "impls": Object({
                "textDocument": Object({
                    "uri": String(
                        "file:///Users/tomas/Documents/sqlparser-rs/src/ast/mod.rs",
                    ),
                }),
                "position": Object({
                    "line": Number(
                        1321,
                    ),
                    "character": Number(
                        11,
                    ),
                }),
            }),
        }),
    ),
}

thread '<unnamed>' panicked at 'index out of bounds: the len is 923 but the index is 1321', crates/ide_db/src/line_index.rs:106:9
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic_bounds_check
   3: rust_analyzer::from_proto::text_range
   4: rust_analyzer::handlers::handle_code_lens_resolve
   5: rust_analyzer::dispatch::RequestDispatcher::on::{{closure}}::{{closure}}
   6: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[Error - 5:33:00 PM] Request codeLens/resolve failed.
  Message: server panicked: index out of bounds: the len is 923 but the index is 1321
  Code: -32603 
```
At `Rust Analyzer Client` I get: 
```
INFO [9/3/2021, 5:32:38 PM]: Extension version: 0.2.727
INFO [9/3/2021, 5:32:38 PM]: Using configuration {
  cargoRunner: null,
  runnableEnv: null,
  inlayHints: {
    enable: false,
    smallerHints: true,
    chainingHints: true,
    maxLength: 25,
    parameterHints: true,
    typeHints: true
  },
  updates: { channel: 'stable', askBeforeDownload: false },
  server: { path: null, extraEnv: null },
  trace: { server: 'off', extension: false },
  debug: {
    engine: 'auto',
    sourceFileMap: {
      '/rustc/<id>': '${env:USERPROFILE}/.rustup/toolchains/<toolchain-id>/lib/rustlib/src/rust'
    },
    openDebugPane: false,
    engineSettings: {}
  },
  assist: {
    importGranularity: 'crate',
    importEnforceGranularity: true,
    importPrefix: 'plain',
    importGroup: true,
    allowMergingIntoGlobImports: true
  },
  callInfo: { full: true },
  cargo: {
    autoreload: true,
    allFeatures: false,
    unsetTest: [ 'core' ],
    features: [],
    runBuildScripts: true,
    useRustcWrapperForBuildScripts: true,
    noDefaultFeatures: false,
    target: null,
    noSysroot: false
  },
  checkOnSave: {
    enable: true,
    allFeatures: null,
    allTargets: true,
    command: 'check',
    noDefaultFeatures: null,
    target: null,
    extraArgs: [],
    features: null,
    overrideCommand: null
  },
  completion: {
    addCallArgumentSnippets: true,
    addCallParenthesis: true,
    postfix: { enable: true },
    autoimport: { enable: true },
    autoself: { enable: true }
  },
  diagnostics: {
    enable: true,
    enableExperimental: true,
    disabled: [],
    remapPrefix: {},
    warningsAsHint: [],
    warningsAsInfo: []
  },
  experimental: { procAttrMacros: false },
  files: { watcher: 'client', excludeDirs: [] },
  highlightRelated: {
    references: true,
    exitPoints: true,
    breakPoints: true,
    yieldPoints: true
  },
  highlighting: { strings: true },
  hover: { documentation: true, linksInHover: true },
  hoverActions: {
    debug: true,
    enable: true,
    gotoTypeDef: true,
    implementations: true,
    references: false,
    run: true
  },
  joinLines: {
    joinElseIf: true,
    removeTrailingComma: true,
    unwrapTrivialBlock: true,
    joinAssignments: true
  },
  lens: {
    debug: true,
    enable: true,
    implementations: true,
    run: true,
    methodReferences: false,
    references: false,
    forceCustomCommands: true
  },
  linkedProjects: [],
  lruCapacity: null,
  notifications: { cargoTomlNotFound: true },
  procMacro: { enable: false, server: null },
  runnables: { overrideCargo: null, cargoExtraArgs: [] },
  rustcSource: null,
  rustfmt: {
    extraArgs: [],
    overrideCommand: null,
    enableRangeFormatting: false
  },
  workspace: { symbol: { search: { scope: 'workspace', kind: 'only_types' } } }
}
INFO [9/3/2021, 5:32:38 PM]: PersistentState: {
  lastCheck: undefined,
  nightlyReleaseId: undefined,
  serverVersion: '0.2.727'
}
INFO [9/3/2021, 5:32:38 PM]: Using server binary at /Users/tomas/Library/Application Support/Code/User/globalStorage/matklad.rust-analyzer/rust-analyzer-x86_64-apple-darwin
```
and at `Rust Analyzer Language Server Trace` I don't get any output.

**Comment by lnicola** [comment]
Not a file, a JSON map with the two keys, one to enable logging and one to redirect the logs to a file (otherwise they spam the Code console).

**Comment by tvallotton** [comment]
is this ok? In my workspace settings I suppose. 
```
{
    "RA_LOG=lsp_server": ["debug", "error"],
    "RA_LOG_FILE": "/Users/tomas/Documents/sqlparser-rs/output"
}
```

**Comment by dzvon** [comment]
@tvallotton I think the right format is:
```
{
    "rust-analyzer.server.extraEnv": {
        "RA_LOG": "lsp_server=debug,error",
        "RA_LOG_FILE": "/Users/tomas/Documents/sqlparser-rs/output"
    },
}
```

**Comment by tvallotton** [comment]
Ok so I just pushed the logs at [output.txt](https://github.com/tvallotton/sqlparser-rs/blob/rust-analyzer-panic/output.txt). If you need anything else just let me know.

**Comment by lnicola** [comment]
Yeah, it looks fine, but it's very short and I think it contains no edits. I would have expected something in the range of tens of MBs, with LSP being so verbose.

On the other hand, I'm not sure we're flushing the log, so the last line or two might be truncated.

**Comment by matklad** [comment]
One hypothesis I have is maybe the clined indeed sends `DidChangeTextDocument` between asking for code lens and asking to resolve a specific code lens? One way to debug this is to add an optional memdoc document version to codelens data and verify, in resolve, that it is the same. 

But in general I think I see a bug here -- we shouldn't assume that between list/resolve calls the state of world doesn't change. We shouldn't be storying text ranges in the resolve data at all, for that matter. 

Instead, we should use the pattern we employ for code actions and completion -- re-run the same query, and use id of the *result* as data.

**Comment by bencarter4185** [comment]
I'm not sure if this is relevant, but I have been getting errors when using rust-analyzer with VS Code, lately. I can't offer any backtraces but I can report that this was with nightly Rust (fully updated) as the default, and I was using the crate [inline-python](https://crates.io/crates/inline-python) within the code, which relies on nightly Rust. rust-analyzer [was also having trouble](https://users.rust-lang.org/t/silencing-rust-analyzer-not-implemented-errors/64292) with macro calls in this crate so I had also disabled checking for macro-errors.

Changing back to stable Rust and removing this inline-python dependency appears to have removed any backtraces in the analyzer. Hope this helps. I can also try and capture some backtraces if desired.

**Comment by Veykril** [comment]
#11182 silences the panic, but the main problem described here still persists

**Comment by Veykril** [comment]
Closing this for now, we've made some changes here again so this is likely a stale issue
