### ISSUE TITLE
unresolved_macro_call for valid macro

### ISSUE THREAD

**Issue by peat** [rust-lang/rust-analyzer#13406]
**rust-analyzer version**: `db2a7087b 2021-12-13 stable`

**rustc version**: `rustc 1.64.0 (a55dd71d5 2022-09-19)`

**relevant settings**:
* VSCode on Arch Linux (package `community/code 1.72.0-1`)
* rust-analyzer plugin v0.2.853

**STR**

* Clone the [Diesel repo](https://github.com/diesel-rs/diesel), and go to any example project, like `diesel/examples/sqlite/getting_started_step_3`
* Open the project in `code` and navigate to the `schema.rs` file.
* I see the attached screenshot with the error in it.
* I can build the project cleanly with `cargo build`

![2022-10-12_15-04](https://user-images.githubusercontent.com/13174/195457051-21d87ce9-f4a0-4652-ae7c-5bc474816e14.png)

**Comment by stagrim** [comment]
The code package in the community repo is an open source build from the vscode github. Other builds then the official ones are not allowed to use the regular extension repositories. The open source build in the arch repo therefor uses the [open vsx](https://open-vsx.org/) repo. The version of rust analyzer there is pretty old, hence why this error occurs. [This comment](https://github.com/rust-lang/rust-analyzer/issues/11080#issuecomment-998704967) shows ways of solving the issue. 

I solved by installing the arch package `community/rust-analyzer`, which is the latest available binary. After installing the binary you can just set the key `rust-analyzer.server.path` of the vscode extension to the rust-analyzer path (in my case `/usr/bin/rust-analyzer`). This hopefully solves your problem.

**Comment by lnicola** [comment]
Keep in mind that you'll still get an old version of the Code extension, which can cause problems, especially related to non-LSP functionality.

**Comment by stagrim** [comment]
Yes, manually installing the `rust-analyzer-no-server.vsix` from the github release with help from the [installation guide](https://rust-analyzer.github.io/manual.html#manual-installation) solves that problem. Hopefully the issues surrounding open-vsx will be solved soon to avoid having to fix it manually.

**Comment by jonas-schievink** [comment]
The OpenVSX issues have been resolved, so closing this.
