### ISSUE TITLE
Cannot activate rust-analyzer server: e.replace is not a function

### ISSUE THREAD

**Issue by woody77** [rust-lang/rust-analyzer#13442]
**rust-analyzer version**: rust-analyzer version: 0.4.1251-standalone

**rustc version**: rustc 1.66.0-nightly (6b6610b8b 2022-10-06)

**relevant settings**:
Let me know what you else might be needed, and how I can help debug this.

**Comment by bjorn3** [comment]
Could you please give the full error with stacktrace?

**Comment by jhgg** [comment]
This issue is all kinds of bizarre. It only occurs when both rust-analyzer and the `ms-python.python` extension are installed. Additionally it only seems to occur on rust-analyzer pre-release.

**Comment by Veykril** [comment]
Pre-release makes sense as its most likely a problem with https://github.com/rust-lang/rust-analyzer/pull/13426. I just installed the python extension and r-a starts up fine for me though. mind sharing your rust-analyzer related settings?

**Comment by jhgg** [comment]
It seems to depend on which extension boots first. Try to reload vscode with a python file open. 

https://user-images.githubusercontent.com/5489149/196911666-09e594fe-4cad-49e6-8aec-9eafec532bb8.mov

**Comment by Veykril** [comment]
Can't seem to trigger that myself, https://github.com/rust-lang/rust-analyzer/pull/13444 should fix the stacktrace being hidden. I'll kick off another nightly once thats merged.

**Comment by jhgg** [comment]
Logs for you:
```
2022-10-20 17:20:38.247 [error] RangeError: Maximum call stack size exceeded
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
2022-10-20 17:20:38.249 [error] RangeError: Maximum call stack size exceeded
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
	at Object.get client [as client] (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:551)
2022-10-20 17:20:38.449 [error] Activating extension rust-lang.rust-analyzer failed due to an error:
2022-10-20 17:20:38.449 [error] TypeError: e.replace is not a function
	at String.replaceAll (/home/discord/.vscode-server-insiders/extensions/ms-python.python-2022.16.1/out/client/extension.js:2:157562)
	at fS (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:40:15201)
	at qi (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:40:15296)
	at qi (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:40:15415)
	at qi (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:40:15415)
	at qi (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:40:15415)
	at da.getClient (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:1502)
	at async da.activate (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:1715)
	at async RS (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:97:1636)
	at async bS (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:97:1125)
	at async S._activate (/home/discord/.vscode-server-insiders/bin/7ef8e6b87a2a5a25ba1ef946bd1640ca3510956c/out/vs/workbench/api/node/extensionHostProcess.js:89:8304)
	at async S._waitForDepsThenActivate (/home/discord/.vscode-server-insiders/bin/7ef8e6b87a2a5a25ba1ef946bd1640ca3510956c/out/vs/workbench/api/node/extensionHostProcess.js:89:8246)
	at async S._initialize (/home/discord/.vscode-server-insiders/bin/7ef8e6b87a2a5a25ba1ef946bd1640ca3510956c/out/vs/workbench/api/node/extensionHostProcess.js:89:7610)

```

**Comment by Veykril** [comment]
Im' sorry but what? Does the python extension overwrite the `String.replaceAll` function or how is r-a calling into that here???
```
2022-10-20 17:20:38.449 [error] TypeError: e.replace is not a function
	at String.replaceAll (/home/discord/.vscode-server-insiders/extensions/ms-python.python-2022.16.1/out/client/extension.js:2:157562)
	at fS (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:40:15201)
	at qi (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:40:15296)
	at qi (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:40:15415)
	at qi (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:40:15415)
	at qi (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:40:15415)
	at da.getClient (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:1502)
	at async da.activate (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:95:1715)
	at async RS (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:97:1636)
	at async bS (/home/discord/.vscode-server-insiders/extensions/rust-lang.rust-analyzer-0.4.1252-linux-x64/out/main.js:97:1125)
	at async S._activate (/home/discord/.vscode-server-insiders/bin/7ef8e6b87a2a5a25ba1ef946bd1640ca3510956c/out/vs/workbench/api/node/extensionHostProcess.js:89:8304)
	at async S._waitForDepsThenActivate (/home/discord/.vscode-server-insiders/bin/7ef8e6b87a2a5a25ba1ef946bd1640ca3510956c/out/vs/workbench/api/node/extensionHostProcess.js:89:8246)
	at async S._initialize (/home/discord/.vscode-server-insiders/bin/7ef8e6b87a2a5a25ba1ef946bd1640ca3510956c/out/vs/workbench/api/node/extensionHostProcess.js:89:7610)
```

**Comment by woody77** [comment]
Today, with `rust-analyzer version: 0.4.1252-standalone` I'm getting the same stacktrace as @jhgg.

I also have `ms-python.python` installed, and I can reproduce this with that extension disabled (and also if I uninstall it).  Even with only a single rust file open.

However, I'm running `vscode-remote`, but after also uninstalling the python extension locally, I'm still seeing the stack trace (but not the failure to start the rust-analyzer server error message).

**Comment by woody77** [comment]
The python extension is patching String, and that's interfering with other extensions?

(I wonder if other `ms-<lang>.*` extensions are doing the same?)

**Comment by Veykril** [comment]
So the problem seems to be the `replaceAll` call here https://github.com/rust-lang/rust-analyzer/blob/master/editors/code/src/config.ts#L194

This is defined as 
```ts
interface String {
    /**
     * Replace all instances of a substring in a string, using a regular expression or search string.
     * @param searchValue A string to search for.
     * @param replaceValue A string containing the text to replace for every successful match of searchValue in this string.
     */
    replaceAll(searchValue: string | RegExp, replaceValue: string): string;

    /**
     * Replace all instances of a substring in a string, using a regular expression or search string.
     * @param searchValue A string to search for.
     * @param replacer A function that returns the replacement text.
     */
    replaceAll(searchValue: string | RegExp, replacer: (substring: string, ...args: any[]) => string): string;
}
```

by the typescript node module. So the prototype fiddling by them seems to change the method resolution here...

**Comment by Veykril** [comment]
So, I don't think there is an alternative for `replaceAll(RegExp, replace: ...): string` we can use here though, so I would be inclined to say that this stupid prototype patching is their mistake (tbf I'd keep that stance even if we can manage to get around this issue).

**Comment by jhgg** [comment]
I concur, maybe we should open an issue on that extension...

**Comment by yotamofek** [comment]
I don't think it's a method resolution issue, the polyfill they're using doesn't support the [`replacement`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replaceAll#parameters) param being a callback. It's trying to unescape the replacement, but ends up calling `.replace` on a function.
I think the easiest solution on RA's side would be to just use `String.replace` with the ['global' regex mod](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace#using_the_global_and_ignorecase_flags_with_replace) (which is how the polyfill is implemented anyways).

**Comment by yotamofek** [comment]
I'll be happy to try and whip up a PR if no one wants to claim it first :)

**Comment by Veykril** [comment]
Feel free to :)

**Comment by jhgg** [comment]
Why do they need to polyfill tho? Vscode runs a new v8/chromium version. Is the polyfill like not even needed?

**Comment by yotamofek** [comment]
> Why do they need to polyfill tho? Vscode runs a new v8/chromium version. Is the polyfill like not even needed?
That's what I was thinking, but maybe the extensions are built to possibly be run on https://vscode.dev ?

It's definitely worth opening an issue about it. Even just using a truly compatible pollyfill will be an improvement.

**Comment by jhgg** [comment]
@Veykril can you kick a new nightly build?

**Comment by Veykril** [comment]
done

**Comment by yotamofek** [comment]
I can confirm the issue is resolved on latest pre-release on my end.

**Comment by Veykril** [comment]
Thanks again, I also fixed the stack overflow in the logs (surprised the extension works even with that overflow happening)
