### ISSUE TITLE
Problems (related to `Sized`) with old rustc versions

### ISSUE THREAD

**Issue by jhgg** [rust-lang/rust-analyzer#20487]
cc  #20443 - this does not repro in stable release. 

**rust-analyzer version**: 0.4.2586-standalone (a905e3b21b 2025-08-18)

**rustc version**: rustc 1.89.0-nightly (99e7c15e8 2025-06-01)

**editor or extension**: VSCode

**relevant settings**: N/A

**code snippet to reproduce**:

```rust
trait Foo {
    fn bar(&self) -> u32 {
        0xCAFE
    }
}

fn debug(_: &dyn Foo) {}

impl Foo for i32 {}

fn main() {
    debug(&1);
     //   ^^ expected &dyn Foo, found &i32
}
```

Similar to #20489, the error does not occur if the impl of `Foo` has no methods, e.g.

```rust
trait Foo { }
```

**Comment by flodiebold** [comment]
Coercion still uses Chalk, so this is an old bug.

**Comment by jhgg** [comment]
> Coercion still uses Chalk, so this is an old bug.

This does not repro in stable though.

**Comment by jhgg** [comment]
I minimized the repro to not involve serde.

**Comment by ShoyuVanilla** [comment]
Those trait object coercion issues (this and https://github.com/rust-lang/rust-analyzer/issues/20489) might be related to the first item in https://github.com/rust-lang/rust-analyzer/issues/20422 . I'll give this a try.

**Comment by Austaras** [comment]
But testing on master with
```rust
    check_no_mismatches(
        r#"
//- minicore: coerce_unsized, dispatch_from_dyn
trait Foo {
    fn bar(&self) -> u32 {
        0xCAFE
    }
}

fn debug(_: &dyn Foo) {}

impl Foo for i32 {}

fn main() {
    debug(&1);
}"#,
    );
```
reports no error.

**Comment by ChayimFriedman2** [comment]
You're right, it's fixed on master. Not sure what fixed it, though. I'll add a test and close this.

**Comment by ShoyuVanilla** [comment]
Funny that I've started next-solver migration of inference table to fix this issue but this has been fixed somehow 😂 Of course inference table migration should be done for many reasons.

**Comment by jhgg** [comment]
I do not think this is actually fixed. I am trying latest nightly (r0.4.2604-standalone (fa19df2d0e 2025-09-04))

<img width="520" height="311" alt="Image" src="https://github.com/user-attachments/assets/ea8a3972-7358-4323-bba4-e1c75812737b" />

Error is still very much present. #20489 is also not fixed as well.

**Comment by ChayimFriedman2** [comment]
I get no error:

<img width="1599" height="647" alt="Image" src="https://github.com/user-attachments/assets/43505a0e-674a-4a73-9502-3cf832bd75b1" />

`rust-analyzer diagnostics` does not report an error either. Are you sure you are using the latest r-a?

**Comment by jhgg** [comment]
> I get no error:
> 
> <img alt="Image" width="1599" height="647" src="https://private-user-images.githubusercontent.com/24700207/486459663-43505a0e-674a-4a73-9502-3cf832bd75b1.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTczNjQ2OTIsIm5iZiI6MTc1NzM2NDM5MiwicGF0aCI6Ii8yNDcwMDIwNy80ODY0NTk2NjMtNDM1MDVhMGUtNjc0YS00YTczLTk1MDItM2NmODMyYmQ3NWIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA5MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwOTA4VDIwNDYzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwNmE5YjA3NDY5NDk4Y2ZjZjNkZmNhODFjNGQ5MGQzODE5Y2QyNDY3MjdhYzk0ZWExZTEyYjIyNDJlYTBjYWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.9JwoJGvZLLsg9RMK-MkWt4xumXQm_supJFFvRDzFBik">
> `rust-analyzer diagnostics` does not report an error either. Are you sure you are using the latest r-a?

Yes, I'm sure. I'm on the latest nightly, 0.4.2607-standalone (a53b44412d 2025-09-05)

It is perhaps due to my compiler version? rustc 1.89.0-nightly (99e7c15e8 2025-06-01)

**Comment by ChayimFriedman2** [comment]
> It is perhaps due to my compiler version? rustc 1.89.0-nightly (99e7c15e8 2025-06-01)

Unlikely, but can you try latest stable?

**Comment by jhgg** [comment]
I think that it is indeed a rustc version issue. It will repro on `rustc 1.88.0 (6b00bc388 2025-06-23)` but not `rustc 1.89.0 (29483883e 2025-08-04)`

**Comment by jhgg** [comment]
Bisection of nightly releases, `nightly-2025-06-17` is the last bad nightly, the issue does not reproduce on `nightly-2025-06-18`. So the problematic commit is one of https://github.com/rust-lang/rust/compare/45acf54eea118ed27927282b5e0bfdcd80b7987c...f3db63916e541ff039ac3cd7364c2d612749b61b

**Comment by ChayimFriedman2** [comment]
If I had to guess, that's the `Sized` hierarchy changes.

The question is whether we want to gate it for versions affected or just ignore the old versions.

**Comment by jhgg** [comment]
Should we re-open this issue in the interim given the issue repros on latest-1 rustc stable version?

**Comment by ChayimFriedman2** [comment]
I've opened it but as I said, I'm not sure we'll end up addressing it.

I do wonder why the rustc version impacts r-a though... I don't remember a relevant place we call rustc.

**Comment by jhgg** [comment]
The commits in this range, touch `library/*` e.g. https://github.com/rust-lang/rust/commit/d43da6f4de19ccfc6ac5a8e6b16ab8cf2893692a 

I am fairly certain this commit is the culprit, applying the changes to `library/core/src/marker.rs` from that commit onto `nightly-2025-06-17` fixes the issue.

**Comment by ChayimFriedman2** [comment]
@ShoyuVanilla, as the one who implemented the `Sized` hierarchy adaptation, how hard do you think it will be to support older rustc versions and do you think it's worth it?

**Comment by ShoyuVanilla** [comment]
I'm not sure what's going on with the old version exactly as I haven't looked closely enough, but my work wasn't something that supporting `Sized` hierarchy in a "correct" way. It was just a makeshift fix that "translates" new `MetaSized`/`PointeeSized` bounds into old `?Sized` bounds, so it's quite surprising that old versions aren't working well.
I guess it would be related to `lower_nextsolver.rs` that might be lacking of such translation or something inside next-solver that demands lang items `MetaSized` and `PointeeSized`.
If the former is the cause it would be not too hard to fix but if the later is the case, I think there's not much we could do

**Comment by ChayimFriedman2** [comment]
I don't think it's the new solver demanding the lang items as that'll cause a panic.

The `Sized` hierarchy was just my guess, although I don't see other things that could've caused this.

**Comment by ShoyuVanilla** [comment]
Then might be the former, I guess? In that case, I believe it wouldn't be a big problem and we could fix it with low efforts. I'll look into this once I'm finished on https://github.com/rust-lang/rust-analyzer/pull/20578 but if there's someone willing to investigate this, that would be great, of course

**Comment by smmalis37** [comment]
The snippet no longer produces an error for me, I only get a dead_code warning on bar.

**Comment by ChayimFriedman2** [comment]
@smmalis37 Are you on rustc 1.89.0-nightly (https://github.com/rust-lang/rust/commit/99e7c15e81385b38a8186b51edc4577d5d7b5bdd 2025-06-01)?

**Comment by smmalis37** [comment]
Ah no, I was on stable rustc, but a prerelease build of rust-analyzer at the time.

**Comment by ChayimFriedman2** [comment]
This bug is only triggered on old rustc.
