### ISSUE TITLE
Ram usage grows incredibly fast with minimal changes

### ISSUE THREAD

**Issue by Calcoph** [rust-lang/rust-analyzer#20949]
**rust-analyzer version**: rust-analyzer version: 1.93.0-nightly (292be5c7 2025-10-29)

**rustc version**: rustc 1.93.0-nightly (292be5c7c 2025-10-29)

**editor or extension**: VSCode rust-analyzer

**relevant settings**: `"rust-analyzer.server.path": "C:\\Users\\Calcoph\\.cargo\\bin\\rust-analyzer"`

So, to establish a baseline, I have a project with the following Cargo.toml:

```
[package]
name = "test_repo"
version = "0.1.0"
edition = "2024"

[dependencies]
#wgpu = "24.0.1"
```

Note that wgpu is commennted out, that's for later.

There is a single source file inside `./src/`

main.rs:

```
fn main() {

}
```

Windows task manager shows rust-analyzer.exe at 360MB

I will be modifying the project. After each modification I hit "restart server" on vscode and wait until RAM usage settles.

Once I uncomment the wgpu dependency, the RAM usage is at 1,022MB. For context, wgpu is a pretty big crate.

Now main.rs contains the following:

```
fn main() {

}

impl A for B {

}
```

The RAM usage is already at 1,169MB

New main.rs content:
```
fn main() {

}

impl A for B {
    fn f(&mut self) {

    }
}
```

Now it is at 1,434MB

```
fn main() {

}

impl A for B {
    fn f(&mut self) {
        match g {
            C::D(e) => self.resized(f),
        }
    }
}
```

Now at 1,442MB. Until here the jumps weren't big, but quite bigger than what I expected (except the wgpu introduction)

Here is the one that worries me the most:
```
fn main() {

}

impl A for B {
    fn f(&mut self) {
        match g {
            C::D(e) => self.resized(e),
        }
    }
}
```

It is now at 5.775MB That is a 4GB jump by renaming a parameter from `f` to `e`.

Of course this final function is a very reduced example of the project I'm working on, which now uses so much RAM that I can no longer run RA for the project, and I'm on a 32GB machine.

EDIT:

For completeness sake, I forgot to add the case where main.rs contains the final contents but there is now wgpu dependency. In that case, the RAM usage is much lower at 616. The wgpu dependency is important for this ticket, even though at no point has wgpu been referenced in main.rs

**Comment by jlizen** [comment]
> rust-analyzer version: rust-analyzer version: 1.93.0-nightly (292be5c7 2025-10-29)

@Calcoph this is a rustc version, not a rust-analyzer version? What RA version is this?

(I'm chasing some other memory issues that seem to coincide with recent releases, haven't filed any issues yet)

**Comment by Calcoph** [comment]
That is what VSCode's command says. I have rust-analyzed installed from rustup, In the relevant settings i've put it as a "custom" rust-analyzer path.

**Comment by jlizen** [comment]
What is the result of `/path/to/rustup/install/of/rust-analyzer --version` ?

**Comment by Calcoph** [comment]
I have removed the custom settings and rerun the RA version command. It now shows `rust-analyzer version: 0.3.2660-standalone (7c810e9994 2025-10-27)`. Now this code:

```
fn main() {
    match g {
        e => a(e),
    }
}
```
needs "only" 2,212MB. While it was 6,000MB with the "custom" version (the one installed by rustup)

**Comment by Calcoph** [comment]
/path/rust-analyzer --version shows the exact same as in the original issue

**Comment by jlizen** [comment]
Gotcha, apologies, I must just not have looked at a rustup-install rust-analyzer version string before!

**Comment by jlizen** [comment]
I'd be interested in whether you see similar issues from the latest release of rust-analyzer (2025-10-28). There were some known memory issues in prior releases (with the new trait solver) that supposedly have been resolved:

Ref: https://github.com/rust-lang/rust-analyzer/issues/20917#issuecomment-3457933167

**Comment by Calcoph** [comment]
I have switched to pre-release version: `rust-analyzer version: 0.4.2663-standalone (f7de8ae045 2025-10-30)` It now uses ~2,000, which is 200MB less than before, but still 1GB more than if I remove the match statement and just leave an empty main. If I rename `e` to `f`, it is now 1,626. Which to me indicates that there's still an issue

**Comment by Calcoph** [comment]
I have tried to follow the instructions on that issue, but compilation fails with `cargo build --features dhat --profile dev-rel`

**Comment by ChayimFriedman2** [comment]
@Calcoph what is the error?

**Comment by ChayimFriedman2** [comment]
@Calcoph Nevermind, found it myself. Can you try with https://github.com/rust-lang/rust-analyzer/pull/20956? (Should be merged soon).

**Comment by Calcoph** [comment]
It does build now. However, it appears to do nothing. I set `rust-analyzer.server.path` to the binary I just built, and `rust-analyzer.profiling.memoryProfile` to `C:\\Users\\....\\mem.log`.

RA doesn't create the mem.log file. And if I create it myself, nothing is written to it. The RA logs show nothing in VSCode.

I've also tried the same thing building with `cargo xtask install --enable-profiling` instead and unsetting `rust-analyzer.server.path`. VSCode does report the version of my extension as `v0.5.0-dev`, but the file is not created, and if I creat it myself, it is not written to.

**Comment by ChayimFriedman2** [comment]
Did you invoke "rust-analyzer: Memory Usage (Clears Database)"?

**Comment by Calcoph** [comment]
The command actually works. Here are the results:

The name of the file indicates:

1. whether wgpu was in the Cargo.toml file
2. whether the main function was empty or contained the mentioned switch statement
3. The amount of RAM windows task manager reported on rust-analyzer

[switch_852MB.log](https://github.com/user-attachments/files/23286736/switch_852MB.log)
[wgpu_empty_main_1770MB.log](https://github.com/user-attachments/files/23286734/wgpu_empty_main_1770MB.log)
[wgpu_switch_3103MB.log](https://github.com/user-attachments/files/23286735/wgpu_switch_3103MB.log)
[empty_main_516MB.log](https://github.com/user-attachments/files/23286737/empty_main_516MB.log)

**Comment by ChayimFriedman2** [comment]
@Calcoph I can't load the profile, are you sure you compiled with `--profile dev-rel`?

I also can't reproduce, the memory usage with the `match` is not different than without it for me.

**Comment by Calcoph** [comment]
The those logs were with just the "xtask" thing. Now I am on the "xtask" extension version (v0.5.0-dev) and I also set `rust-analyzer.server.path` to the binary in `target/dev-rel` I hope it works this time.

[switch_837MB.log](https://github.com/user-attachments/files/23286992/switch_837MB.log)
[wgpu_switch_3112MB.log](https://github.com/user-attachments/files/23286993/wgpu_switch_3112MB.log)
[wgpu_empty_main_1772MB.log](https://github.com/user-attachments/files/23286990/wgpu_empty_main_1772MB.log)
[empty_main495MB.log](https://github.com/user-attachments/files/23286991/empty_main495MB.log)

Things that might be important to take into account:
* The ram usage is not instantaneous, it is a slow but constant increase until it reaches a stable point.
* When the RAM usage stabilizes, a warning log like this appears: `2025-11-01T22:58:03.3619315+01:00 ERROR overly long loop turn took 7.5868067s (event handling took 7.586779s): Request(Request { id: RequestId(I32(30)), method: "rust-analyzer/memoryUsage", params: Null })` Or maybe it was this one `2025-11-01T22:57:40.6913862+01:00 ERROR overly long loop turn took 2.3217022s (event handling took 2.3216554s): PrimeCaches(End { cancelled: false })` I'm not too sure

**Comment by ChayimFriedman2** [comment]
@Calcoph Thanks, it works now. I didn't analyze the profile in depth, but from what I see, there is nothing exceptional here, and the cost should be mostly one-time. As such, I'm closing this issue.

**Comment by Calcoph** [comment]
@ChayimFriedman2 I wouldn't say there is nothing exceptional. The fact that a 5 line program uses 1.4GB more than an empty program is exceptional on itself. More so considering that the difference without declaring a library of that same program is "only" 350MB. Without even using said library in the program itself.

I don't see what is one-time about the issue. Once the program has that piece of code, that's 1.4GB less of RAM I have in my system. It doesn't go away, and it only grows as the project gets larger.

And as I am seeing, I'm not the only one having RAM usage issues. #20370 #19402 #17408 #14956 These are all issues with RAM with unknown origin.

I was annoyed with r-a's high RAM usage and decided to see what was causing it instead of making yet another "r-a uses a lot of RAM" generic post. And I am quite confident I've found a good hint as to where one of the issues might be.

I understand and it's fine that there might not be enough resources since it is an open-source project. But closing the issue without fixing it is burying the head under the sand. I much rather have a permanently-opened issue with low priority for years because lack of resources than it being closed and dismissed as a non-issue.

**Comment by ChayimFriedman2** [comment]
I investigated the profiles you gave, and determined the cause, and this is the reason I closed this issue. To elaborate a bit more - the memory comes from the trait solving which we don't have to do with empty main but do have to do with even a tiny bit of code with it, and it's one-time in the sense that adding more code won't result in other jumps of 1GB, rather a linear growth.

I appreciate trying to help us investigate the cause of the memory consumption, but I can pretty confidently say yours is unrelated to the ones you linked (and some of them are just general complaints about r-a using a lot of RAM), and also, as I said, not unexpected. Therefore closing the issue is the appropriate action.
